#  https://kubernetes.io/docs/concepts/configuration/secret/
# 
# 
# Create a Secret
#  https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data
# 

# Create a Secret
#  https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#create-a-secret

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==

# Use the following for the data: mongo-user & mongo-password
# echo -n mongouser | base64
# 
# 
# Thi PowerShell commands will provide you  the equivalent of encoding the string "mongouser" to base64.
# $echoedText = [System.Text.Encoding]::UTF8.GetBytes("mongouser")
# $base64Text = [System.Convert]::ToBase64String($echoedText)
# echo $base64Text



# Create the Secret

# kubectl apply -f https://k8s.io/examples/pods/inject/secret.yaml
# View information about the Secret:

# kubectl get secret test-secret
# Output:

# NAME          TYPE      DATA      AGE
# test-secret   Opaque    2         1m
# View more detailed information about the Secret:

# kubectl describe secret test-secret
# Output:

# Name:       test-secret
# Namespace:  default
# Labels:     <none>
# Annotations:    <none>

# Type:   Opaque

# Data
# ====
# password:   13 bytes
# username:   7 bytes
